recipes-connectivity/suite-connector/files/config.json, recipes-connectivity/suite-connector/suite-connector.inc, recipes-connectivity/suite-connector/suite-connector_git.bb
[#13] Make logs storage configurable for the Kanto Suite Connector recipe
=> Make logs storage configurable for the Kanto Suite Connector recipe

recipes-connectivity/suite-bootstrapping/files/config.json, recipes-connectivity/suite-bootstrapping/files/service.template, recipes-connectivity/suite-bootstrapping/suite-bootstrapping.inc, recipes-connectivity/suite-bootstrapping/suite-bootstrapping_git.bb
[#3] Yocto recipe for Kanto Suite Bootstrapping
=> Yocto recipe for Kanto Suite Bootstrapping

recipes-monitoring/system-metrics/system-metrics.inc
[#19] Use one and the same wording for the system metrics component
=> Use one and the same wording for the system metrics component

recipes-management/software-update/files/config.json, recipes-management/software-update/files/service.template, recipes-management/software-update/software-update.inc, recipes-management/software-update/software-update_git.bb
[#7] Yocto recipe for Kanto Software Update
=> Yocto recipe for Kanto Software Update

recipes-containers/container-management/container-management.inc, recipes-containers/container-management/container-management_git.bb, recipes-containers/container-management/files/config.json, recipes-containers/container-management/files/service.template
[#6] Yocto recipe for Kanto Container Management
=> Yocto recipe for Kanto Container Management

LICENSE, NOTICE.md, README.md
[#29] Apply the new Eclipse Kanto project license scheme
Signed-off-by: Konstantina Gramatova <konstantina.gramatova@bosch.io>
=> Apply the new Eclipse Kanto project license scheme

recipes-management/file-backup/file-backup.inc, recipes-management/file-backup/file-backup_git.bb, recipes-management/file-backup/files/config.json, recipes-management/file-backup/files/service.template
[#23] Yocto recipe for Kanto File Backup
=> Yocto recipe for Kanto File Backup

recipes-management/file-backup/file-backup.inc, recipes-management/file-backup/file-backup_git.bb, recipes-management/file-backup/files/config.json
[#33] Specify a default storage location in the file-backup's configuration
=> Specify a default storage location in the file-backup's configuration

recipes-connectivity/local-digital-twins/local-digital-twins_git.bb, recipes-connectivity/suite-bootstrapping/suite-bootstrapping_git.bb, recipes-connectivity/suite-connector/suite-connector_git.bb, recipes-containers/container-management/container-management_git.bb, recipes-management/file-backup/file-backup_git.bb, recipes-management/file-upload/file-upload_git.bb, recipes-management/software-update/software-update_git.bb, recipes-monitoring/system-metrics/system-metrics_git.bb
[#36] Provide Kirkstone fixed M2 layer
Prepared the Kirkstone branch for upstream work.
Signed-off-by: Konstantina Gramatova <konstantina.gramatova@bosch.io>
=> Provide Kirkstone fixed M2 layer

SECURITY.md
[#40] Incorporate the Eclipse security policy
- SECURITY.md initial version
Signed-off-by: Evgeni Grigorov <Evgeni.Grigorov@bosch.io>
=> Eclipse security policy for Kanto Yocto layer

SECURITY.md
[#40] Incorporate the Eclipse security policy
- SECURITY.md initial version
Signed-off-by: Evgeni Grigorov <Evgeni.Grigorov@bosch.io>
=> Eclipse security policy for Kanto Yocto layer - Kirkstone

conf/layer.conf
=> Support for Langdale

.github/workflows/validation.yml
[#37] Ensure automated integration testing
=> Ensure automated integration testing

.github/workflows/validation.yml, conf/layer.conf
[#52] Switch GitHub workflow to use mickledore release
Signed-off-by: Kristiyan Gostev <kristiyan.gostev@bosch.com>
=> Change workflow job to use mickledore

.github/workflows/validation.yml
[#54] Add the kirkstone branch to the GitHub workflow
Signed-off-by: Kristiyan Gostev <kristiyan.gostev@bosch.com>
=> Add kirkstone branch in the github validation workflow

.github/workflows/validation.yml, recipes-containers/container-management/container-management_git.bb
[#56] Add validation workflow in the `kirkstone` branch
Signed-off-by: Kristiyan Gostev <kristiyan.gostev@bosch.com>
=> Add validation workflow and fix container management revision

.github/workflows/validation.yml, recipes-containers/container-management/container-management_git.bb
[#58] Use go mix-in repository
=> Use go mix-in repository

.github/workflows/validation.yml, recipes-management/update-manager/files/config.json, recipes-management/update-manager/files/service.template, recipes-management/update-manager/update-manager.inc, recipes-management/update-manager/update-manager_git.bb
[#60] Yocto recipe for Kanto Update Manager
Signed-off-by: Stoyan Zoubev <Stoyan.Zoubev@bosch.io>
=> Yocto recipe for Kanto Update Manager (kirkstone branch)

recipes-management/update-manager/files/service.template
[#63] Wrong argument in update manager service unit template
=> Fix update-manager.service ExecStart command

recipes-management/update-manager/files/config.json, recipes-management/update-manager/files/service.template, recipes-management/update-manager/update-manager_git.bb
[#67] Update recipe for Kanto Update Manager
=> Update recipe for Kanto Update Manager

recipes-connectivity/local-digital-twins/local-digital-twins_git.bb, recipes-connectivity/suite-bootstrapping/suite-bootstrapping_git.bb, recipes-connectivity/suite-connector/suite-connector_git.bb, recipes-containers/container-management/container-management_git.bb, recipes-management/file-backup/file-backup_git.bb, recipes-management/file-upload/file-upload_git.bb, recipes-management/software-update/software-update_git.bb, recipes-management/update-manager/update-manager_git.bb, recipes-monitoring/system-metrics/system-metrics_git.bb
[#71] Provide Kirkstone fixed M4 layer
=> Provide Kirkstone fixed M4 layer

recipes-connectivity/local-digital-twins/local-digital-twins_git.bb, recipes-connectivity/suite-bootstrapping/suite-bootstrapping_git.bb, recipes-connectivity/suite-connector/suite-connector_git.bb, recipes-containers/container-management/container-management_git.bb, recipes-management/file-backup/file-backup_git.bb, recipes-management/file-upload/file-upload_git.bb, recipes-management/software-update/software-update_git.bb, recipes-management/update-manager/update-manager_git.bb, recipes-monitoring/system-metrics/system-metrics_git.bb
[#72] Provide fixed M4 layer for the main branch
=> Provide fixed M4 layer for the main branch

.github/workflows/validation.yml, recipes-connectivity/aws-connector/aws-connector.bb, recipes-connectivity/aws-connector/aws-connector.inc, recipes-connectivity/aws-connector/files/config.json, recipes-connectivity/aws-connector/files/service.template
[#78] Yocto recipe for Kanto AWS Connector (kirkstone branch)
=> [#78] Yocto recipe for Kanto AWS Connector (kirkstone branch)

.github/workflows/validation.yml, recipes-connectivity/azure-connector/azure-connector.inc, recipes-connectivity/azure-connector/azure-connector_git.bb, recipes-connectivity/azure-connector/files/config.json, recipes-connectivity/azure-connector/files/service.template
[#22] Add azure-connector recipe.
Signed-off-by: Ivan Marinov <ivan.marinov@bosch.io>
=> [#22] Add azure-connector recipe.

.github/workflows/validation.yml, recipes-connectivity/azure-connector/azure-connector.inc, recipes-connectivity/azure-connector/azure-connector_git.bb, recipes-connectivity/azure-connector/files/config.json, recipes-connectivity/azure-connector/files/service.template
[#81] Add azure connector recipe.
Signed-off-by: Ivan Marinov <ivan.marinov@bosch.io>
=> [#81] Add azure connector recipe for kirkstone branch.

recipes-connectivity/local-digital-twins/local-digital-twins_git.bb, recipes-connectivity/suite-bootstrapping/suite-bootstrapping_git.bb, recipes-connectivity/suite-connector/suite-connector_git.bb, recipes-containers/container-management/container-management_git.bb, recipes-management/file-backup/file-backup_git.bb, recipes-management/file-upload/file-upload_git.bb, recipes-management/software-update/software-update_git.bb, recipes-management/update-manager/update-manager_git.bb, recipes-monitoring/system-metrics/system-metrics_git.bb
Reverts eclipse-kanto/meta-kanto#74
=> Revert "Provide Kirkstone fixed M4 layer"

recipes-connectivity/local-digital-twins/local-digital-twins_git.bb, recipes-connectivity/suite-bootstrapping/suite-bootstrapping_git.bb, recipes-connectivity/suite-connector/suite-connector_git.bb, recipes-containers/container-management/container-management_git.bb, recipes-management/file-backup/file-backup_git.bb, recipes-management/file-upload/file-upload_git.bb, recipes-management/software-update/software-update_git.bb, recipes-management/update-manager/update-manager_git.bb, recipes-monitoring/system-metrics/system-metrics_git.bb
Reverts eclipse-kanto/meta-kanto#73
=> Revert "Provide fixed M4 layer for the main branch"

recipes-containers/container-management/container-management_git.bb, recipes-containers/container-management/files/service.template
[#88] Build container management as a static binary - Kirkstone branch
=> Build container management as a static binary - Kirkstone branch

recipes-connectivity/aws-connector/aws-connector_git.bb, recipes-connectivity/azure-connector/azure-connector_git.bb, recipes-connectivity/local-digital-twins/local-digital-twins_git.bb, recipes-connectivity/suite-connector/suite-connector_git.bb, recipes-containers/container-management/container-management_git.bb, recipes-management/file-backup/file-backup_git.bb, recipes-management/file-upload/file-upload_git.bb, recipes-management/software-update/software-update_git.bb, recipes-management/update-manager/update-manager_git.bb, recipes-monitoring/system-metrics/system-metrics_git.bb
[#98] Provide fixed v1.0.0 layer for the kirkstone branch
=> Provide fixed v1.0.0 layer for the kirkstone branch

recipes-connectivity/aws-connector/aws-connector_git.bb, recipes-connectivity/azure-connector/azure-connector_git.bb, recipes-connectivity/local-digital-twins/local-digital-twins_git.bb, recipes-connectivity/suite-connector/suite-connector_git.bb, recipes-containers/container-management/container-management_git.bb, recipes-management/file-backup/file-backup_git.bb, recipes-management/file-upload/file-upload_git.bb, recipes-management/software-update/software-update_git.bb, recipes-management/update-manager/update-manager_git.bb, recipes-monitoring/system-metrics/system-metrics_git.bb
[#96] Provide fixed v1.0.0 layer for the main branch
=> Provide fixed v1.0.0 layer for the main branch

recipes-connectivity/aws-connector/aws-connector_git.bb, recipes-connectivity/azure-connector/azure-connector_git.bb, recipes-connectivity/local-digital-twins/local-digital-twins_git.bb, recipes-connectivity/suite-connector/suite-connector_git.bb, recipes-containers/container-management/container-management_git.bb, recipes-management/file-backup/file-backup_git.bb, recipes-management/file-upload/file-upload_git.bb, recipes-management/software-update/software-update_git.bb, recipes-management/update-manager/update-manager_git.bb, recipes-monitoring/system-metrics/system-metrics_git.bb
[#100] Revert Provide fixed v1.0.0 layer for the main branch
=> [#100] Revert Provide fixed v1.0.0 layer for the main branch

recipes-connectivity/aws-connector/aws-connector_git.bb, recipes-connectivity/azure-connector/azure-connector_git.bb, recipes-connectivity/local-digital-twins/local-digital-twins_git.bb, recipes-connectivity/suite-connector/suite-connector_git.bb, recipes-containers/container-management/container-management_git.bb, recipes-management/file-backup/file-backup_git.bb, recipes-management/file-upload/file-upload_git.bb, recipes-management/software-update/software-update_git.bb, recipes-management/update-manager/update-manager_git.bb, recipes-monitoring/system-metrics/system-metrics_git.bb
[#104] Revert Provide fixed v1.0.0 layer for the scarthgap branch
=> [#104] Revert Provide fixed v1.0.0 layer for the scarthgap branch #104

recipes-connectivity/aws-connector/aws-connector_git.bb, recipes-connectivity/azure-connector/azure-connector_git.bb, recipes-connectivity/local-digital-twins/local-digital-twins_git.bb, recipes-connectivity/suite-connector/suite-connector_git.bb, recipes-containers/container-management/container-management_git.bb, recipes-management/file-backup/file-backup_git.bb, recipes-management/file-upload/file-upload_git.bb, recipes-management/software-update/software-update_git.bb, recipes-management/update-manager/update-manager_git.bb, recipes-monitoring/system-metrics/system-metrics_git.bb
[#102] Revert Provide fixed v1.0.0 layer for the Kirkstone branch
=> [#102] Revert Provide fixed v1.0.0 layer for the Kirkstone branch #102
